### ISSUE TITLE
ERROR: could not find a version that satisfies the requirement torch==1.15.0

### ISSUE THREAD

**Issue by lizhuoran-nlp** [cheniison/e2e-coref-pytorch#1]
ERROR: Could not find a version that satisfies the requirement torch==1.15.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0)
ERROR: No matching distribution found for torch==1.15.0

When I install torch=1.15.0, it happened.
Could you confirm that torch's version is 1.15.0 or others?

**Comment by cheniison** [comment]
The torch version is 1.5.0.
Thank you for pointing out the mistake, I have fixed the error in README.md.
