### ISSUE TITLE
loss直接降为0的问题

### ISSUE THREAD

**Issue by 20XYSong** [cheniison/e2e-coref-pytorch#10]
我想请问博主，训练的时候经常出现loss直接降为0的情况正常吗？我查看了对应gold_scores，发现很多-inf

**Comment by cheniison** [comment]
见 https://github.com/cheniison/e2e-coref-pytorch/issues/6#issuecomment-809012772

**Comment by 20XYSong** [comment]
谢谢博主！但我尝试了在原有loss上加了 加权BCE Loss/Focal Loss(期望模型能在前m个spans中捕获更多的gold spans)，训练时打印原有loss和BCE_Loss的值，发现仍存在原有Loss快速降为0 的情况，不知道这是否是需要加大BCELoss的权重，或是有其他的训练技巧呢？还是说只要训练步数足够大，这个问题就可以得到解决呢？

**Comment by cheniison** [comment]
加入加权BCE Loss/Focal Loss无法解决这个问题。由于模型参数在刚开始训练时是随机初始化的，coarse to fine pruning 机制会随机选择句子中的 span。候选span的数量是远大于gold spans的，因此大概率不会选择到gold spans，更难同时选择出共指的spans。但只有在同时选择出共指的gold spans时，整个模型才会朝着我们希望的方向优化，损失前的权重才会起作用。

至少在我实验的过程中，有三个方法能处理该问题：
（1）加大训练数据集规模。在有大量的不同的数据输入时，总会碰到共指spans同时出现的训练样例且模型不容易过拟合到所有spans都是不共指的情况。
（2）模型热启动。预先训练一个 coarse to fine pruning 的模型而不使用随机初始化，让它在整个模型刚开始训练时就能尽量找到相对准确的 spans，而不是随机选择 spans
（3）加入mention detection loss，见上面回复中提到的 #6 里的描述

如果有其他方案，欢迎交流。

**Comment by 20XYSong** [comment]
谢谢博主解答！您第二点的意思是否是，预训练一个基于stage1和stage2筛选的模型，使得我们通过前两阶段的初筛能保证获得的topKspans中大部分为gold span。在此基础上再进行e2e训练，这样方能保证模型按照我们期望的方向优化。

**Comment by cheniison** [comment]
是的，是这个意思。另外我问一个题外的问题，你们是看的哪个博客，方便把博客链接发我一下吗，我去拜读一下。我没有发布过相关的博客，应该是其他博主写的博客中引用了我的这个项目。

**Comment by 20XYSong** [comment]
谢谢博主！我是直接在Git上找相关项目时发现您的项目的，不是通过博客找到的呢。

**Comment by cheniison** [comment]
哦哦，好的
