### ISSUE TITLE
训练停不下来

### ISSUE THREAD

**Issue by lalala1020** [cheniison/e2e-coref-pytorch#11]
博主，您好，我用自己的数据在您的模型上训练，一直停不下来，已经训练二十多天了，请问博主这个正常吗？请问博主训练的时候用了多长时间呀？

**Comment by cheniison** [comment]
这个是手动停止的，看到验证集上效果差不多了就可以人工结束进程，模型会保存效果最好那次的参数

**Comment by lalala1020** [comment]
哦莫，谢谢博主！
