### ISSUE TITLE
请问可以提供训练好的模型文件吗

### ISSUE THREAD

**Issue by harukaza** [cheniison/e2e-coref-pytorch#13]
作者您好，非常感谢您分享关于e2e的pytorch版本。请问您能分享训练好的模型文件以便直接用来作为模型提取指代关系工具吗？

**Comment by cheniison** [comment]
抱歉，由于时间比较久远了，没有找到当时已训练好的模型文件

**Comment by harukaza** [comment]
好的，再次感谢您的回复 : )
