### ISSUE TITLE
train 发生错误

### ISSUE THREAD

**Issue by ysys444** [cheniison/e2e-coref-pytorch#15]
你好！
打扰一下。
实现代码时出错。

train.py 

coref_model(sentences_ids, sentences_masks, sentences_valid_masks, speaker_ids, sentence_map, subtoken_map, genre, transformer_model)

当我运行这部分时，我收到以下错误：
TypeError: only integer tensors of a single element can be converted to an index

我很好奇如何解决这个问题。

**Comment by cheniison** [comment]
请检查一下输入的格式是否正确，依赖包的版本是否与readme中说明的一致
