### ISSUE TITLE
哥，这个配上ontonotes5.0就可以跑了吗

### ISSUE THREAD

**Issue by BugMaker-99** [cheniison/e2e-coref-pytorch#4]

**Comment by cheniison** [comment]
对的。下载了ontonotes5.0相关数据以后，照着readme里的步骤操作，中文上应该是没有问题的（其他语言没有测试很多，可能需要修改数据预处理部分）。如果有问题，可以直接提issue。

**Comment by BugMaker-99** [comment]
好的，非常感谢，我就是做中文指代消解
