### ISSUE TITLE
”top_span_ratio“指的是什么

### ISSUE THREAD

**Issue by houliangxue** [cheniison/e2e-coref-pytorch#8]
请问一下：model.py 第267行
m = min(int(self.config["top_span_ratio"] * len(tokens_embed)), spans_len)    # 文本中最多的span数量
这个”top_span_ratio“代表什么意思，为什么是乘以len(tokens_embed)，而不是len(spans_embed)

**Comment by cheniison** [comment]
一段文本中最多存在的候选 span 的数量，该数量与文档字数成比例。详细说明见论文中 \lambda 参数的相关描述。
