### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lalala1020** [cheniison/e2e-coref-pytorch#9]
博主 您好！请问可以将中文是的数据发一份给我吗，我去官网下载遇到了一些困难，拜托了  1305855209@qq.com

**Comment by cheniison** [comment]
对不起，由于版权限制，我无法将数据发给您。您可以参照 [https://www.zhihu.com/question/67166283](https://www.zhihu.com/question/67166283)，得到数据集的下载权限。

**Comment by lalala1020** [comment]
> 对不起，由于版权限制，我无法将数据发给您。您可以参照 https://www.zhihu.com/question/67166283，得到数据集的下载权限。

好的 谢谢您

**Comment by lalala1020** [comment]
您好，那方便告诉我数据集的大小吗（train.json，test.json文件大概是多少条数据）？我打算用自己的数据跑，但是不清楚需要多少条。本来打算下载ontonotes数据集回来看数据量的，但是官方那边认证一直没有完成。拜托啦

**Comment by cheniison** [comment]
训练集大概有1810+篇文档，验证集250+篇，测试集218篇文档。每篇文档几十到上千字不等。具体可见论文 [
CoNLL-2012 shared task: Modeling Multilingual Unrestricted Coreference in OntoNotes](https://dl.acm.org/doi/10.5555/2391181.2391183)

**Comment by lalala1020** [comment]
> 训练集大概有1810+篇文档，验证集250+篇，测试集218篇文档。每篇文档几十到上千字不等。具体可见论文 [ CoNLL-2012 shared task: Modeling Multilingual Unrestricted Coreference in OntoNotes](https://dl.acm.org/doi/10.5555/2391181.2391183)

感谢！
